apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crm
  template:
    metadata:
      labels:
        app: crm
    spec:
      containers:
      - name: crm-container
        image: myrepo/crm-service:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: crm-service
spec:
  selector:
    app: crm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
